language: c
sudo: false
addons:
  apt:
    sources:
      - avsm
    packages:
      - ocaml
      - ocaml-native-compilers
      - opam
      - texlive-latex-recommended
branches:
  except:
    - opam/unstable
    - opam/testing
script: bash -ex ./src/tools/ci/travis.bash
env:
  - OPAM_SWITCH=system
  - OPAM_SWITCH=3.12.1
  - OPAM_SWITCH=4.01.0
  - OPAM_SWITCH=4.02.2
  - OPAM_SWITCH=4.03.0
  - OPAM_SWITCH=4.04.0
  - OPAM_SWITCH=4.05.0
  - OPAM_SWITCH=4.06.0
  - OPAM_SWITCH=4.07.0
  - OPAM_SWITCH=4.08.0
  - OPAM_SWITCH=4.08.0+flambda
cache:
  directories:
  - $HOME/.opam
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f47ff4ebe702f6acd4e0
    on_success: always
    on_failure: always
    on_start: never
